
package tian.pusen.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceImplPortType", targetNamespace = "http://service.pusen.tian/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceImplPortType {


    /**
     * 
     * @param name
     * @param info
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.pusen.tian/")
    @RequestWrapper(localName = "saveInfo", targetNamespace = "http://service.pusen.tian/", className = "tian.pusen.service.SaveInfo")
    @ResponseWrapper(localName = "saveInfoResponse", targetNamespace = "http://service.pusen.tian/", className = "tian.pusen.service.SaveInfoResponse")
    public String saveInfo(
        @WebParam(name = "name", targetNamespace = "http://service.pusen.tian/")
        String name,
        @WebParam(name = "info", targetNamespace = "http://service.pusen.tian/")
        String info);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.pusen.tian/")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.pusen.tian/", className = "tian.pusen.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.pusen.tian/", className = "tian.pusen.service.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "http://service.pusen.tian/")
        String name);

}
